Integracion de funciones de iniciar sesion, cerrar sesion, registrars…
corp-0/artemanga pull request #126
Opened 2022-05-07 20:57 UTC by kanroot

Se integraron las funcionalidades previamente construidas de iniciar sesión, logout registrarse, y modificar perfil, estas funcionalidades se ocultan o aparecen si el usuario se loguea o no.

fixes #112

2022-05-07 21:33 UTC, corp-0 requested changes

2022-05-07 21:33 UTC, corp-0 commented on src/cuenta_usuario/views.py
> +    usuarios_permitidos = [TipoUsuario.CLIENTE, TipoUsuario.ADMINISTRADOR]
cambia el permiso para aceptar todos
```suggestion
    usuarios_permitidos = VistaRestringidaMixin.todos_los_usuarios
```

2022-05-07 21:33 UTC, corp-0 commented on src/templates/web/base.html
> +                    <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/manga.png' %}" width="150"
encuentro más difícil de leer esta versión que la anterior

2022-05-07 21:33 UTC, corp-0 commented on src/templates/web/base.html
> +                                <li><a class="dropdown-item" href="{% url 'productos-por-categoria' i.id %}">{{ i }}</a>
igual, arbitrario dejar el cierre del ``li`` abajo solo

2022-05-07 21:33 UTC, corp-0 commented on src/templates/web/base.html
> +                                </li>
cierre del li abajo solo sin ningún motivo

2022-05-07 21:33 UTC, corp-0 commented on src/templates/web/base.html
> +                    {% if user.is_authenticated %}
este dropdown no debería remplazar el área donde ahora está saludando al usuario?

2022-05-08 16:05 UTC, kanroot commented on src/templates/web/base.html
> +                    {% if user.is_authenticated %}
Ya hice los cambios, maté el saludo, para que aceptes el pull.

2022-05-08 16:10 UTC, kanroot commented
@corp-0  no tengo ni idea el motivo por el cual okteto está dando error, no me muestra los detalles.

2022-05-08 16:56 UTC, corp-0 commented
> @corp-0 no tengo ni idea el motivo por el cual okteto está dando error, no me muestra los detalles.

Es normal, hasta que se mergee el pr de okteto

2022-05-08 19:28 UTC, kanroot commented
> > @corp-0 no tengo ni idea el motivo por el cual okteto está dando error, no me muestra los detalles.
> 
> Es normal, hasta que se mergee el pr de okteto

sigue con el mismo error.

2022-05-08 19:33 UTC, corp-0 commented
Ya vi cuál es el error, tal parece que la preview no va a funcionar si la branch que hace el pull request viene de otra repo. Voy a tener que corregir eso usando otro trigger en GitHub actions, quizás lo puedo resolver.

2022-05-08 19:34 UTC, corp-0 approved these changes

2022-05-08 19:34 UTC, merged