Mis compras
corp-0/artemanga pull request #154
Opened 2022-05-20 20:09 UTC by kanroot

Se agrego la vista de "mis compras".
Se agrego un acceso directo al admin de django y para volver a la tienda.
Correcciones ortograficas.

fixes #151

2022-05-21 20:52 UTC, corp-0 requested changes
Pequeñas correcciones. Lo del script de datos de prueba puede que no parezca importante pero lo es porque podemos usar ese script para automaizar pruebar y sería tonto que nos fallara por algo como que estemos generando los datos mal.

2022-05-21 20:52 UTC, corp-0 commented on src/datos_prueba/management/commands/generar_ventas.py
> +                usuario=random.choice(Usuario.objects.filter(tipo_usuario=TipoUsuario.CLIENTE.value).all())
toma el usuario desde despacho. Con esta implementación de la generación de datos de prueba, la mayoría del tiempo vas a tener un usuario asociado a la venta y otro al despacho, completamente diferente.

2022-05-21 20:52 UTC, corp-0 commented on src/templates/administración/base.html
> +                        <a href="{% url 'home' %}" class="nav-link">Tienda</a>
```suggestion
                        <a href="{% url 'home' %}" class="nav-link">Volver a tienda</a>
```

2022-05-21 20:52 UTC, corp-0 commented on src/venta/models.py
> +        return f"Su pedido será enviado a {self.direccion}"
agrega el "Su pedido será enviado a" al template, no a la representación textual de este objeto. La misma representación puede ser usada en varios otros lados, como tablas o vistas de administración.

2022-05-21 22:04 UTC, corp-0 commented on src/templates/web/mis_compras.html
> +{% extends 'web/base.html' %}return f"Su pedido será enviado a {self.direccion}"
pasaste a llevar el control + v

2022-05-21 22:05 UTC, kanroot commented on src/templates/web/mis_compras.html
> +{% extends 'web/base.html' %}return f"Su pedido será enviado a {self.direccion}"
xd

2022-05-21 22:06 UTC, kanroot commented on src/templates/web/mis_compras.html
> +{% extends 'web/base.html' %}return f"Su pedido será enviado a {self.direccion}"
ahi quedo

2022-05-22 01:38 UTC, corp-0 approved these changes

2022-05-22 01:38 UTC, merged