Modelos
corp-0/artemanga pull request #43
Opened 2022-04-08 21:29 UTC by kanroot

Este commit contiene la creación de los distintos componentes y sus respectivos modelos

2022-04-08 23:30 UTC, corp-0 commented
por qué cerraste?

2022-04-08 23:55 UTC, kanroot commented
Estoy viendo como conectar a la base datos para realizar las migraciones, esta dando error en las migraciones 
` RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': could not translate host name "db" to address: Name or service not known`

2022-04-09 00:38 UTC, corp-0 commented
estás corriendo la base de datos usando el docker? Si no, puedes hacer ``sudo docker-compose -f dev-compose up db``. También tendrías que cambiar en el ``.env`` el ``DB_HOST`` de ``db`` a ``localhost``

2022-04-09 03:02 UTC, corp-0 requested changes
Hiciste caleta man, yo creí que ibas a hacer los modelos del sprint nomás. Te pedí unos cambios que se repiten en casi todos los modelos, vas a tener que hacer la migración de nuevo si, mejor haz los cambios y no migres hasta que revise y te diga que está todo bien.

2022-04-09 03:02 UTC, corp-0 commented on src/inventario/models.py
> +    iva = models.IntegerField(verbose_name="iva", blank=False, default=19)
este campo lo discutimos en su momento pero creo que no debería ser un miembro de Producto porque al final si cambia el IVA les cambia a todos, no sólo a este producto

2022-04-09 20:51 UTC, corp-0 requested changes

2022-04-09 20:51 UTC, corp-0 commented on src/cuentausuario/apps.py
> +    name = 'cuentausuario'
nombre del módulo

2022-04-09 20:51 UTC, corp-0 commented on src/venta/models.py
> +    # productos = models.ManyToManyField('Producto', through='VentaProducto')
esto lo resolviste con una foreignkey en producto, verdad? Quita el código comentado nomás

2022-04-09 21:06 UTC, kanroot commented on src/artemangaweb/settings.py
> +AUTH_USER_MODEL = 'cuentausuario.Usuario'
Se me olvido cambiarlo xd

2022-04-10 02:07 UTC, corp-0 commented on src/cuenta_usuario/apps.py
> +class CuentausuarioConfig(AppConfig):
```suggestion
class CuentaUsuarioConfig(AppConfig):
```

2022-04-11 01:10 UTC, corp-0 approved these changes

2022-04-11 03:02 UTC, merged